### ISSUE TITLE
Chrome Store version

### ISSUE THREAD

**Issue by Ein-Tim** [roberrrt-s/legacy-verified-extension#3]
Are you planning to submit this extension to the Chrome Store?

**Comment by roberrrt-s** [comment]
Hi @Ein-Tim — the earliest version (`0.1.0`) was submitted on April 22nd. The latest version has been submitted on April the 24th and is pending review, I will update this issue as soon as it's live.

**Comment by roberrrt-s** [comment]
Hi @Ein-Tim 

It's live.

https://chrome.google.com/webstore/detail/legacy-verified/kpaemodmgoobmechkcplpffkpfbpebnm
